# Generated by Django 3.0.8 on 2020-07-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='pesel_number',
            new_name='pesel',
        ),
    ]
